#!/bin/bash

# howto discusses valgrind suppression files and how to create
# your own.
#
# https://wiki.wxwidgets.org/Valgrind_Suppression_File_Howto
#
#
# This test is almost pointless given that we had to suppress
# warnings due to leaks in all the GTK libraries.
#


set -e

if ! which valgrind > /dev/null ; then
    echo "valgrind was not found in your PATH"
    exit 1
fi


cat << END

 This test is almost pointless given that we had to suppress valgrind
 warnings due to leaks in all the GTK libraries, which are very leaky.
 I can't come up with a valgrind suppression file that has any bite.
 The valgrind --gen-suppressions=all option makes very long valgrind
 suppression files.  I give up.  quickscope is shitty code that depends
 on shitty code (GTK).


END


cd "$(dirname ${BASH_SOURCE[0]})"

pre="$PWD"

export VaLGRIND_RuN="valgrind\
 --quiet\
 --tool=memcheck\
 --leak-check=full\
 --trace-children=yes\
 --show-leak-kinds=all\
 --trace-children-skip='*'\
 --suppressions="${pre}/valgrind_suppressions"\
 --errors-for-leak-kinds=all\
 --error-exitcode=211"


exec ./run_tests $*


# notes below here:

exit 1


export VaLGRIND_RuN="valgrind\
 --quiet\
 --tool=memcheck\
 --leak-check=full\
 --trace-children=yes\
 --show-leak-kinds=all\
 --trace-children-skip='*'\
 --gen-suppressions=all\
 --suppressions="${pre}/valgrind_suppressions"\
 --errors-for-leak-kinds=all\
 --error-exitcode=211"


# --gen-suppressions=all\
